myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='myapp'

urlpatterns = [
    path('home/',views.ProductsListView.as_view(),name='home'),
    path('product/<int:pk>/',views.ProductsDetailView.as_view(),name='product_detail'),
    path('product/add/',views.addproduct,name='addproduct'),
    path('product/update/<int:id>',views.Update,name='update'),
    path('product/delete/<int:id>',views.Delete,name='delete'),
    path('product/mylistings',views.listings,name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='apicheckoutsession'),
    path('about',views.about,name='about'),

    


]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls'))
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('create/',views.create,name='create'),
    path('created/',views.created,name='created'),
    

    
    


]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Products(models.Model):
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse('myapp:home')
        
    seller=models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    desc=models.CharField(max_length=200)
    image=models.ImageField(blank=True,upload_to='images')


class OrderDetail(models.Model):
    cutomer_username=models.CharField(max_length=200)
    product=models.ForeignKey(to='Products',on_delete=models.PROTECT)
    amount=models.IntegerField()
    stripe_payment_intent=models.CharField(max_length=200)
    has_paid=models.BooleanField(default=False)
    created_on=models.DateField(auto_now_add=True)
    updated_on=models.DateField(auto_now_add=True)

myapp/views.py
from django.shortcuts import render,redirect
from . models import Products,OrderDetail
from django.views.generic import ListView,DetailView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView

from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy,reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import stripe


# Create your views here.

# def home(request):
#     product=Products.objects.all()
#     produt=request.GET.get('product')
#     paginator=paginator
 
#     context={
#         'products':product
#     }
#     return render(request,'myapp/home.html',context)


class ProductsListView(ListView):
    model=Products
    template_name='myapp/home.html'
    context_object_name='products'
    paginate_by=8
# def product_detail(request,id):
#     product=Products.objects.get(id=id)
#     context={
#         'product':product
#     } 
#     return render(request,'myapp/detail.html',context)

class ProductsDetailView(DetailView):
    model=Products
    template_name='myapp/detail.html'
    context_object_name='product'
    pk_url_kwarg='pk'
    
    def get_context_data(self,**kwargs):
        context = super(ProductsDetailView,self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY 
        return context



@login_required
def addproduct(request):
    if request.method=='POST':
        if all(list(request.POST.values())):
            name=request.POST.get('name')
            price=request.POST.get('price')
            desc=request.POST.get('desc')
            image=request.FILES['upload']
            seller=request.user
            product=Products(name=name,price=price,desc=desc,image=image,seller=seller)
            product.save()


    return render(request,'myapp/addproduct.html')
# class ProductCreateView(CreateView):
#     model=Products
#     fields=['name','price','desc','image','seller']
    



def Update(request,id):
    
    product=Products.objects.get(id=id)
    if request.method=='POST':
        product.name=request.POST.get('name')
        product.price=request.POST.get('price')
        product.desc=request.POST.get('desc')
        product.image=request.FILES['upload']
        product.save()
        return  redirect('/myapp/home')

    context={
        'product':product
    } 

    return render(request,'myapp/updateproduct.html',context)


def Delete(request,id):
    product=Products.objects.get(id=id)
    context={
        'product':product
    } 
    if request.method=='POST':
        product.delete()
        return redirect('/myapp/home')
    
    return render(request,'myapp/delete.html',context)


def listings(request):
    product=Products.objects.filter(seller=request.user)
    context={
        'products':product
    }
    return render(request,'myapp/mylistings.html',context)

@csrf_exempt
def create_checkout_session(request,id):
    import pdb;pdb.set_trace();
    product=get_object_or_404(Products,pk=id)
    stripe.api_key=settings.STRIPE_SECRET_KEY
    checkout_session=stripe.checkout.Session.create(
        # customer_email=request.user.email,
        customer_email="abc@db.com",
        payment_method_types=['card'],
        line_items=[
            {
                'price_data':{
                    'currency':'usd',
                    'product_data':{
                        'name':product.name,
                    },
                    # 'unit_amount':int(product.price*100),
                    'unit_amount':int(200),
                },
                'quantity':1,
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('myapp:success'))+"?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse('myapp:failed')),

    )

    order=OrderDetail()
    order.cutomer_username=request.user.username
    order.product=product
    # order.stripe_payment_intent=checkout_session['payment_intent']
    order.stripe_payment_intent=200
    order.amount=int(product.price*100)
    order.save()
    return JsonResponse({'sessionId':checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name='myapp/payment_success.html'
    def get(self,request,*args,**kwargs):
        session_id=request.GET.get('seesion_id')
        if session_id is None:
            return HttpResponseNotFound()
        session=stripe.checkout.Session.retrieve(session_id)
        stripe.settings.STRIPE_SECRET_KEY
        order=get_object_or_404(OrderDetail,stripe_payment_intent=session.payment_intent)
        order.has_paid=True
        order.save()
        return render(request,self.template_name)
    
class PaymentFailedView(TemplateView):
    template_name='myapp/payment_failed.html'    


def about(request):
    return render(request,'myapp/about.html')



myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
     {% block content %}
     <div class="grid max-w-screen-xl px-4 pt-20 pb-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 lg:pt-28">
        <div class="mr-auto place-self-center lg:col-span-7">
            <h1 class="max-w-2xl mb-4 text-4xl font-extrabold leading-none tracking-tight md:text-5xl xl:text-6xl dark:text-white">Reuse  &<br>Reduce.</h1>
            <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Let’s mindfully bring a few sustainable choices back to our current lifestyle, starting with technology!<a href="https://tailwindcss.com" class="hover:underline"></a> <a href="https://flowbite.com/docs/getting-started/introduction/" class="hover:underline"></a> <a href="https://flowbite.com/blocks/" class="hover:underline"></a>.</p>
        </div>            
    </div>
    <section class="bg-gray-50 dark:bg-gray-800">
        <div class="max-w-screen-xl px-4 py-8 mx-auto text-center lg:py-24 lg:px-6">
            <figure class="max-w-screen-md mx-auto">
                <svg class="h-12 mx-auto mb-3 text-gray-400 dark:text-gray-600" viewBox="0 0 24 27" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z" fill="currentColor"/>
                </svg> 
                <blockquote>
                    <p class="text-xl font-medium text-gray-900 md:text-2xl dark:text-white">"Business is not financial science, it's about trading.. buying and selling. It's about creating a product or service so good that people will pay for it."</p>
                </blockquote>
                <figcaption class="flex items-center justify-center mt-6 space-x-3">
                    
                    <div class="flex items-center divide-x-2 divide-gray-500 dark:divide-gray-700">
                        <div class="pr-3 font-medium text-gray-900 dark:text-white">Anita Roddick</div>
                        <div class="pl-3 text-sm font-light text-gray-500 dark:text-gray-400"></div>
                    </div>
                </figcaption>
            </figure>
        </div>
      </section>
     {% endblock %}
    
</body>
</html>

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
     {% block content %}
       <a  class="flex py-3 px-4" href="{% url 'myapp:addproduct' %}"> 
        <img class="w-20 h-20 m-6" src="{% static 'images/add.png' %}" alt="">
        <h1 class="text-3xl font-bold text-gray-600 py-7 px-3 m-3">Add Product</h1>
       </a>
        <form class="bg-white rounded shadow-xl m-10 px-14 py-9 w-3/5" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 font-bold py-1" for="">Product Name</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Name" name="name" id="name"> 
            </div>
            <div class="py-3 mb-2">
                <label class="block text-gray-700 font-bold py-1"  for="">Price</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Price" name="price" id="price">    
            </div>
            <div class="py-3 ">
                <label class="block text-gray-700 font-bold py-1" for="">Description</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Desccription" name="desc" id="desc">
            </div>
            
           <div class="py-3 mb-2">
            <label class="block text-gray-700 font-bold py-1" for="">Product Image</label>
            <input  class="rounded py-1 text-gray-500" type="file" accept="image/*" placeholder="" name="upload" id="upload">
           </div>
            
            <div class="py-2">
            <input class="btn bg-green-400 rounded text-white mb-2 px-5 py-2 hover:text-green-700" type="submit" name="" value="Add Product"  id="">
        </div>

        </form>

     {% endblock %}
    
</body>
</html>

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static '/myapp/styles.css'%}">
        
     </head>
<body>
    <nav class="flex shadow-md justify-between items-center">
        <div class="flex">
            <a class="flex px-6 py-2" href="{% url 'myapp:home' %}">
            <img class="h-20 w-20" src="{% static 'images/shop.png' %}" alt="">
            <span class="text-gray-500 font-bold text-2xl px-5 py-7">Buy & Sell</span>
            </a>
        </div>
        <div class="pr-16">
            <ul class="flex items-center gap-5 ">
                <li>
                    <a class="hover:text-gray-300 " href="{% url 'myapp:home' %}">Home</a>
                </li>
                <li>
                    <a class="hover:text-gray-300" href="{% url 'myapp:addproduct' %}">Add Product</a>
                </li>
                <li>
                    <a  class="hover:text-gray-300" href="{% url 'myapp:about' %}">About</a>
                </li>
                <li>
                    <a class="hover:text-gray-300" href="{% url 'myapp:mylistings' %}">Profile</a>
                </li>

            </ul>
        </div>
        <div class="pr-4">
            <ul class="flex gap-3">
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="bg-red-500 rounded-md px-4 py-2 hover:bg-red-300">Logout</a>
        </li>

            {% else %}
        <li>   
            <a href="{% url 'users:login' %}" class="bg-yellow-400 rounded-md px-4 py-2 hover:bg-yellow-300">LogIn</a>
        </li> 
         <li>   
            <a href="{% url 'users:register' %}" class="bg-blue-400 rounded-md px-4 py-2 hover:bg-blue-300">SignIn</a>

            {% endif %}
          </li>
            </ul>
        </div>
    </nav>
{% block content %}


{% endblock %}
    
</body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
     {% block content %}
       <a  class="flex py-3 px-4" href="{% url 'myapp:addproduct' %}"> 
        <img class="w-20 h-20 m-6" src="{% static 'images/delete.png' %}" alt="">
        <h1 class="text-3xl font-bold text-gray-600 py-7 px-3 m-3">Delete Product</h1>
       </a>
        <form class="bg-white rounded shadow-xl m-10 px-14 py-9 w-3/5" action="" method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            
            <div class="mb-2">
                <label class="text-2xl block text-gray-700 font-bold py-1" for="">Are you sure want to delete this Product?</label>
                
            </div>
            <div class="text-lg font-bold text-gray-500">
                {{product.name}}
            </div>
            <div>
                <img class="w-72 h-72" src="{{product.image.url}}" alt="">
            </div>
            
            
           
            
            <div class="py-2 ">
            <input class="btn bg-red-400 rounded text-white mb-2 px-5 py-2 hover:text-red-300" type="submit" name="Confirm" value="Delete"  id="">
            <a class="button bg-green-400 rounded text-white mb-2 px-5 py-2 hover:text-green-700" href="{% url 'myapp:home' %}">Cancel </a>
        </div>

        </form>

     {% endblock %}
    
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
   
</head>
<body>
    {% block content %}
    <div class="flex p-6 w-full h-200">
        
        <img class="w-1/2" src="{{product.image.url}}" alt="">
    
        <div class="py-7 text-xl">
            <div class="text-gray-500">{{product.name}}</div>
            <div class="font-bold text-md text-green-400 py-1">₹ {{product.price}}</div>
            <div class="font-semibold text-md py-1">Posted by : <span class="text-indigo-400">{{product.seller}}</span></div>
            <div class="font-semibold text-md py-1">Contact : <span class="">{{product.seller.profile.contact_number}}</span></div>
            <!-- <div class="py-4">
                <button class="bg-green-500 text-white py-1 px-2 rounded" id="checkout">Checkout</button>
            </div> -->
        </div>
        <script src="https://js.stripe.com/v3/"></script>
        <script type="text/javascript">

            var stripe = Stripe('{{ stripe_publishable_key }}')
            var checkoutButton = document.getElementById('checkout')
            checkoutButton.addEventListener('click',function(){
                fetch("{% url 'myapp:apicheckoutsession' id=product.id %}",{method:'POST',})
                .then(function(response){
                    return response.json()
                })
                .then(function(session){
                    return stripe.redirectToCheckout({sessionId:session.sessionId})
                })
                .then(function(result){
                    if(result.error){
                        alert(result.error.message)
                    }
                })
                .catch(function(error){
                    console.error('Error',error)
                })
            })
        </script>
            
       
    </div>



    {% endblock %}
    
</body>
</html>

myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>





{% block content %}

<main class="mt-8 mx-auto max-w-7xl px-10 sm:mt-10 sm:px-6 md:mt-10 lg:mt-10 lg:px-8 xl:mt-20">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-600 sm:text-5xl md:text-5xl px-12">
            <span class="block xl:inline">Premium Products & 

        </span>
        <span class="block text-green-500 xl:inline">
            Non-Premium Products
        </span>
        
    </h1>
<!-- <div class="m-9">
<h2>Search Products</h2>
<form method="get">
    <input class="font-semibold text-lg text-gray-500" name="product" id="" placeholder="Type a product to search" type="text">
</form>
</div> -->
    
    </div>
</main>
<body>
    <div class="p-10 grid grid-cols-3 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-4 lg:grid-cols-4 gap-1">
    
        {% for pro in products %} 
        <!-- /myapp/product/{{pro.id}} -->
        <a href="{% url 'myapp:product_detail' pro.id %}"> 
            <div class="rounded-lg overflow-hidden w-4/5 shadow-xl hover:shadow-2xl dark:hover:shadow-black/30">
                <img  class="w-full h-64 object-contain" src=" {{pro.image.url}}" alt="">
                <div class="px-4">
                    <div class="font-bold text-xl text-grey-900">
                        {{pro.name}}
                    </div>
                    <div class="font-bold text-md text-green-400">
                        ₹ {{pro.price}}  
                    </div>
                    <div class="py-1">
                        <p class="text-gray-500 text-base">{{pro.desc}}</p>
                    </div>

                </div>  
            </div>
            <br>
           
        </a>    
        {% endfor %}
       
    </div>

    <!-- paginate -->
    <div class="pagination flex justify-center items-center mb-20"
    >
        <span>
            {% if page_obj.has_previous %}
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"  href="?page=1"> First </a>
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"  href="?page={{page_obj.previous_page_number}}"> Previous </a>
            {% endif %}
            <span class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" >
          Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
          </span>
       
        {% if page_obj.has_next %}
        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.next_page_number}}"> Next </a>
        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"  href="?page={{page_obj.paginator.num_pages}}"> Last </a>
        {% endif %}
    </span>
    </div>


</body>

{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
   
</head>
<body>
    {% block content %}
    <div class="text-2xl m-10  font-bold">My Listings</div>
    {% for x in products %}
<div class="w-3/4 itemcontainer flex shadow-lg m-10 p-10">
 <span class="w-1/5">
    <img class="w-40 h-40 object-contain" src="{{x.image.url}}" alt="">
</span>
<span class="w-2/5 py-5">
    <div class="font-bold">
        {{x.name}}
    </div>
    <div class="text-green-500 font-bold">
        {{x.price}}
    </div>
</span>
<span class="w-1/5 py-9">
    <a class="bg-green-500 text-white font-semibold px-3 py-2 rounded" href="{% url 'myapp:update' x.id %}">Update</a>

</span>
<span class="w-1/5 py-9">
    <a class="bg-red-500 text-white font-semibold px-3 py-2 rounded" href="{% url 'myapp:delete' x.id %}">Delete</a>

</span>
</div>
{% endfor %}
    {% endblock %}
    
</body>
</html>

myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html' %}
{% block content %}

<p>
Payment Failed
</p>
{% endblock %}

myapp/templates/myapp/payment_success.html
{% extends 'myapp/base.html' %}
{% block content %}

<p>
    We recieved your order,payment was successfull
</p>
{% endblock %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
     {% block content %}
       <a  class="flex py-3 px-4" href="{% url 'myapp:addproduct' %}"> 
        <img class="w-20 h-20 m-6" src="{% static 'images/Update.png' %}" alt="">
        <h1 class="text-3xl font-bold text-gray-600 py-7 px-3 m-3">Update Product</h1>
       </a>
        <form class="bg-white rounded shadow-xl m-10 px-14 py-9 w-3/5" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 font-bold py-1" for="">Product Name</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Name" name="name" id="name" value="{{product.name}}"> 
            </div>
            <div class="py-3 mb-2">
                <label class="block text-gray-700 font-bold py-1"  for="">Price</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Price" name="price" id="price" value="{{product.price}}">    
            </div>
            <div class="py-3 ">
                <label class="block text-gray-700 font-bold py-1" for="">Description</label>
                <input class="shadow appearance-none border rounded py-1 px-3 text-gray-500" type="text" placeholder="Desccription" name="desc" id="desc" value="{{product.desc}}">
            </div>
            
           <div class="py-3 mb-2"> 
            <img class="w-28 h-28 object-contain" src="{{product.image.url}}" alt="">
            <label class="block text-gray-700 font-bold py-1" for="">Product Image</label>
            <input  class="rounded py-1 text-gray-500" type="file" accept="image/*" placeholder="" name="upload" id="upload" value="{{product.image}}">
           </div>
            
            <div class="py-2">
            <input class="btn bg-green-400 rounded text-white mb-2 px-5 py-2 hover:text-green-700" type="submit" name="" value="Update Product"  id="">
        </div>

        </form>

     {% endblock %}
    
</body>
</html>